<?php

namespace ContainerXX5A2As;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserVoterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Security\Voter\UserVoter' shared autowired service.
     *
     * @return \App\Security\Voter\UserVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/UserVoter.php';

        return $container->privates['App\\Security\\Voter\\UserVoter'] = new \App\Security\Voter\UserVoter(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
