<?php

namespace ContainerUf6hmb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QGNWvvwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qGNWvvw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qGNWvvw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'artistRepository' => ['privates', 'App\\Repository\\ArtistRepository', 'getArtistRepositoryService', true],
        ], [
            'artistRepository' => 'App\\Repository\\ArtistRepository',
        ]);
    }
}
