<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXX5A2As\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXX5A2As/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXX5A2As.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXX5A2As\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXX5A2As\App_KernelTestDebugContainer([
    'container.build_hash' => 'XX5A2As',
    'container.build_id' => '989b8ebb',
    'container.build_time' => 1630934689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXX5A2As');
