export default [
  {
    id: 1,
    name: 'Hôtel de Vogüé',
    address: '8 Rue de la Chouette',
    zipCode: 21000,
    city: 'Dijon',
    latitude: 47.331225502922,
    longitude: 5.0438964532017,
    description: "L'Hôtel de Vogüé de Dijon en Côte-d'Or est un hôtel particulier du xviie siècle. Il est situé 8 rue de la Chouette, près du chevet de l'église Notre-Dame. L'hôtel a été classé au titre des monuments historiques le 5 janvier 1911",
    picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Vue_panoramique_de_Dijon_10.jpg/1024px-Vue_panoramique_de_Dijon_10.jpg',
    slug: 'hotel-de-vogue',
    events: [
      {
        id: 1,
        name: 'Vernissage',
        description: "Nous vous invitons, dans la cour de l'ENSA afin de fêter ensemble le commencement d'une belle aventure qui sera jonché de surprises",
        startDatetime: '2022-03-07T19:30:00+00:00',
        endDatetime: '2022-03-07T23:00:00+00:00',
        slug: 'vernissage',
        artists: [
          {
            id: 1,
            firstname: 'WECOMEINPEACE',
            lastname: '',
            picture: 'https://www.flickr.com/photos/_wecomeinpeace/16076592071/',
            description: 'WECOMEINPEACE a été fondé par Wilfried Della Rossa, Kimi Do et Thomas Mathieu Depuis 2008, ils produisent des évènements et des installations autour de concepts innovants et créatifs. Ils puisent leur inspiration dans différents domaines tels que le design, le graphisme, l’architecture et le jeu vidéo.',
            videoLink: 'https://www.youtube.com/watch?v=1xJQ816CTKQ&ab_channel=CHKT',
            slug: 'wecomeinpeace',
            genres: [
              {
                id: 1,
                name: 'Lumière',
                slug: 'lumiere',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Musée des Beaux-Arts de Dijon',
    address: '1 Rue Rameau',
    zipCode: 21000,
    city: 'Dijon',
    latitude: 47.346702168578,
    longitude: 5.0303548436853,
    description: "Le musée des Beaux-Arts de Dijon est l'un des plus importants et l'un des plus anciens musées de France. Situé au cœur de la ville, il occupe l'ancien palais ducal, siège au XVᵉ siècle de l’État bourguignon.",
    picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Entr%C3%A9e_du_mus%C3%A9e_des_Beaux-Arts.jpg/1024px-Entr%C3%A9e_du_mus%C3%A9e_des_Beaux-Arts.jpg',
    slug: 'musee-des-beaux-arts-de-dijon',
    events: [
      {
        id: 2,
        name: 'Apéro Lumière',
        description: "L'équipe CHKT, vous propose un apéro mix qui aura pour objectif de vous faire oublier votre journée de travail",
        startDatetime: '2022-03-07T19:30:00+00:00',
        endDatetime: '2022-03-07T23:00:00+00:00',
        slug: 'apero-lumiere',
        artists: [
          {
            id: 2,
            firstname: 'THEORIZ',
            lastname: '',
            picture: '',
            description: 'Théoriz est un studio de création Art et Technologie spécialisé dans la conception installations immersives et de spectacles audiovisuels innovant',
            videoLink: 'https://vimeo.com/194838088',
            slug: 'theoriz',
            genres: [
              {
                id: 1,
                name: 'Lumière',
                slug: 'lumiere',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'Cour Bareuzai',
    address: '61 Rue des Godrans',
    zipCode: 21000,
    city: 'Dijon',
    latitude: 47.322539724787,
    longitude: 5.0386489109619,
    description: 'Cour Bareuzai se situe à Dijon, Capitale de la région Bourgogne Franche Comté, au sein du centre-ville historique classé depuis juillet 2015 au patrimoine mondial de l’Unesco. Passage atypique, c’est à la fois un lieu unique et central permettant d’offrir une expérience nouvelle grâce à un projet de rénovation ambitieux.',
    picture: 'https://chroniques-architecture.com/wp-content/uploads/2021/04/01-Cour-Bareuzai-Chapman-Taylor-@Stephane-Rouillard.jpg',
    slug: 'cour-bareuzai',
    events: [
      {
        id: 3,
        name: 'Lumière sur cour',
        description: 'test',
        startDatetime: '2022-03-07T19:30:00+00:00',
        endDatetime: '2022-03-07T23:00:00+00:00',
        slug: 'lumiere-sur-cour',
        artists: [
          {
            id: 3,
            firstname: 'SAPIA',
            lastname: '',
            picture: '',
            description: '',
            videoLink: 'https://soundcloud.com/adrienpisa/bebe-requin-dj-set',
            slug: 'sapia',
            genres: [
              {
                id: 2,
                name: 'Musique',
                slug: 'musique',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'La Vapeur',
    address: '42 Avenue de Stalingrad',
    zipCode: 21000,
    city: 'Dijon',
    latitude: 47.405903021743,
    longitude: 5.0602131828532,
    description: 'Site officiel de La Vapeur, scène de musiques actuelles de la ville de Dijon. Concerts, expositions, projections, actions culturelles et artistiques.',
    picture: 'https://www.souchier-boullet.com/wp-content/uploads/2019/01/lavapeur-dijon.jpg',
    slug: 'la-vapeur',
    events: [
      {
        id: 4,
        name: 'Patrimoine illuminé',
        description: 'test',
        startDatetime: '2022-03-07T19:30:00+00:00',
        endDatetime: '2022-03-07T23:00:00+00:00',
        slug: 'patrimoine-illumine',
        artists: [
          {
            id: 4,
            firstname: 'David',
            lastname: 'GUERRA',
            picture: '',
            description: 'Svindrön, aka David Guerra, est un artiste sonore, compositeur, interprète, sound designer et programmeur, vivant en France. Multi-instrumentiste autodidacte et créateur de musique électronique, il se forme à la musique électroacoustique (Conservatoire de Chalon-sur-Saône, avec Jean-Marc WEBER) et aux techniques studio (CFPM Villeurbanne). C’est au travers d’un live électro IDM / techno qu’il fait ses armes sur la scène lyonnaise. Aujourd’hui, par ses pratiques et son parcours, il lie à sa production musicale la précision d’une approche électroacoustique, l’efficacité des rythmes techno, la puissance des nappes de la musique drone et la chaleur boisée d’une guitare, ou, d’une sanza. Sensible à l’art total, David Guerra crée et collabore sur de nombreux projets artistiques où l’art sonore, la danse, l’art visuel, l’art plastique... vivent dans un temps unique.',
            videoLink: 'https://vimeo.com/161602302',
            slug: 'david-guerra',
            genres: [
              {
                id: 1,
                name: 'Lumière',
                slug: 'lumiere',
              },
              {
                id: 2,
                name: 'Musique',
                slug: 'musique',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name: 'Galeries Lafayette',
    address: '41-49 Rue de la Liberté',
    zipCode: 21000,
    city: 'Dijon',
    latitude: 47.437663128279,
    longitude: 5.0141121757522,
    description: "Galeries du Groupe Galeries Lafayette. Le bâtiment se situe à l'angle de la rue du château et de la rue de la Liberté.",
    picture: 'https://cdn-s-www.bienpublic.com/images/3B61ACB0-8B7E-4628-B529-E8F95B0CA2B8/NW_raw/1-quatre-vingt-dix-ans-apres-la-facade-des-galeries-lafayette-a-garde-toute-sa-prestance-en-particulier-en-plein-centre-ville-de-dijon-2-aujourd-hui-le-magasin-bourguignon-propose-plusieurs-centaines-de-marques-photos-p-b-1411740300.jpg',
    slug: 'galeries-lafayette',
    events: [],
  },
  {
    id: 6,
    name: "Cour de l'ENSA",
    address: '3 Rue Michelet',
    zipCode: 21000,
    city: 'Dijon',
    latitude: 47.45752729474,
    longitude: 5.0141120179433,
    description: "La Cour de l'ENSA est la cour de L'École nationale supérieure d'art de Dijon, anciennement l'École nationale des beaux-arts de Dijon.",
    picture: 'https://ensa-dijon.fr/wp-content/uploads/2020/10/cite-internationale-arts-paris.jpg',
    slug: 'cour-de-l-ensa',
    events: [],
  },
  {
    id: 7,
    name: 'Grand Hôtel La Cloche',
    address: '14 Place Darcy',
    zipCode: 21000,
    city: 'Dijon',
    latitude: 47.324328695582,
    longitude: 5.034022511587,
    description: 'Grand Hôtel La Cloche de Dijon est un hôtel 5 étoiles classé monument historique qui propose des chambres et suites en plein centre ville.',
    picture: 'https://imgcy.trivago.com/c_limit,d_dummy.jpeg,f_auto,h_1300,q_auto,w_2000/itemimages/48/69/48691_v4.jpg',
    slug: 'grand-hotel-la-cloche',
    events: [
      {
        id: 5,
        name: 'La forêt de lumière',
        description: 'test',
        startDatetime: '2022-03-07T19:30:00+00:00',
        endDatetime: '2022-03-07T23:00:00+00:00',
        slug: 'la-foret-de-lumiere',
        artists: [
          {
            id: 2,
            firstname: 'THEORIZ',
            lastname: '',
            picture: '',
            description: 'Théoriz est un studio de création Art et Technologie spécialisé dans la conception installations immersives et de spectacles audiovisuels innovant',
            videoLink: 'https://vimeo.com/194838088',
            slug: 'theoriz',
            genres: [
              {
                id: 1,
                name: 'Lumière',
                slug: 'lumiere',
              },
            ],
          },
        ],
      },
    ],
  },
];
