<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUf6hmb7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUf6hmb7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUf6hmb7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUf6hmb7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUf6hmb7\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uf6hmb7',
    'container.build_id' => 'd3ebe163',
    'container.build_time' => 1630931793,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUf6hmb7');
